Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.synced_folder "shared", "/home/vagrant/shared"
  config.vm.provision "shell", path: "mongo-install.sh"
  config.vm.provision "shell", path: "mongo-insert.sh", privileged: false
end